# data_dir: '/sonic_home/josefernandes/datasets/lesaude/mimic-iv-ecg-monolith'
# data_dir: '/scratch/josefernandes/mimic-iv-ecg-monolith'
data_dir: '/snfs2/josefernandes/datasets/lesaude/mimic-iv-ecg-monolith'
train_frac: 1.0
cache: false

# Lance dataset paths (populated by scripts/build_lance.py)
lance_path: '/snfs2/josefernandes/datasets/lesaude/mimic-iv-ecg-monolith/mimic_iv_ecg.lance'
pairs_path: '/snfs2/josefernandes/datasets/lesaude/mimic-iv-ecg-monolith/pairs.lance'
vocabulary_path: '/snfs2/josefernandes/datasets/lesaude/mimic-iv-ecg-monolith/icd_vocabulary_76.json'

# lance_path: '/scratch/josefernandes/18792/data/mimic_iv_ecg.lance'
# pairs_path: '/scratch/josefernandes/18792/data/pairs.lance'
# vocabulary_path: '/scratch/josefernandes/18792/data/icd_vocabulary_76.json'

# lance_path: '/scratch/josefernandes/data/mimic_iv_ecg.lance'
# pairs_path: '/scratch/josefernandes/data/pairs.lance'
# vocabulary_path: '/scratch/josefernandes/data/icd_vocabulary_76.json'

spt_runs_dir: 'runs'